server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**

            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/api/v1/products/**

            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                -Path=/api/v1/inventory/**